from tests.pipeline_base import PipelineTestBase
from tests.pipeline_legacy import PipelineTest as LegacyPipelineTest


class PipelineRegressionTest(PipelineTestBase):
    """Grouped regression tests for historical bugs and boundary conventions."""

    # 这些测试对应明确踩过的坑：最新值误解释历史、时点边界漂移、缓存串仓、benchmark 映射错误。
    test_universe_uses_visible_month_asset_instead_of_latest_asset = LegacyPipelineTest.test_universe_uses_visible_month_asset_instead_of_latest_asset
    test_universe_audit_report_uses_visible_month_asset_not_latest_asset = LegacyPipelineTest.test_universe_audit_report_uses_visible_month_asset_not_latest_asset
    test_universe_audit_report_excludes_entities_missing_latest_month_rows_from_funnel = LegacyPipelineTest.test_universe_audit_report_excludes_entities_missing_latest_month_rows_from_funnel
    test_reports_use_latest_completed_month_instead_of_incomplete_current_month = LegacyPipelineTest.test_reports_use_latest_completed_month_instead_of_incomplete_current_month
    test_monthly_outputs_mark_incomplete_month_as_observation_only = LegacyPipelineTest.test_monthly_outputs_mark_incomplete_month_as_observation_only
    test_available_date_helpers_use_signal_month_end_boundary = LegacyPipelineTest.test_available_date_helpers_use_signal_month_end_boundary
    test_universe_marks_nav_not_available_by_signal_month_end = LegacyPipelineTest.test_universe_marks_nav_not_available_by_signal_month_end
    # 回测与缓存问题一旦回归会直接污染历史结果，因此单独保留在 regression 组。
    test_backtest_uses_continuous_months_and_records_empty_portfolio_months = LegacyPipelineTest.test_backtest_uses_continuous_months_and_records_empty_portfolio_months
    test_backtest_records_missing_return_audit_fields = LegacyPipelineTest.test_backtest_records_missing_return_audit_fields
    test_load_cached_dataset_reads_persisted_sample_snapshot = LegacyPipelineTest.test_load_cached_dataset_reads_persisted_sample_snapshot
    test_load_cached_dataset_rejects_snapshot_from_other_data_source = LegacyPipelineTest.test_load_cached_dataset_rejects_snapshot_from_other_data_source
    test_entity_assets_are_aggregated_across_share_classes = LegacyPipelineTest.test_entity_assets_are_aggregated_across_share_classes
    test_fetch_manager_df_uses_cache = LegacyPipelineTest.test_fetch_manager_df_uses_cache
    test_api_call_uses_persisted_disk_cache = LegacyPipelineTest.test_api_call_uses_persisted_disk_cache
    test_fund_basic_and_fund_company_force_refresh_even_if_disk_cache_exists = LegacyPipelineTest.test_fund_basic_and_fund_company_force_refresh_even_if_disk_cache_exists
    # benchmark 类型映射属于最容易被默认回退掩盖的问题，必须长期保留回归约束。
    test_feature_builder_uses_type_mapped_benchmark = LegacyPipelineTest.test_feature_builder_uses_type_mapped_benchmark
    test_backtest_uses_weighted_type_mapped_benchmark = LegacyPipelineTest.test_backtest_uses_weighted_type_mapped_benchmark
