from tests.pipeline_base import PipelineTestBase
from tests.pipeline_legacy import PipelineTest as LegacyPipelineTest


class PipelineUnitTest(PipelineTestBase):
    """Grouped unit-style tests for local financial and engineering rules."""

    # 基金池局部过滤规则：单独验证门槛和准入条件是否按预期工作。
    test_universe_filters_new_fund_and_low_assets = LegacyPipelineTest.test_universe_filters_new_fund_and_low_assets
    test_universe_filters_holding_period_restricted_fund = LegacyPipelineTest.test_universe_filters_holding_period_restricted_fund
    # 特征构造规则：重点验证窗口计算、可见性边界和事件切分，不依赖完整实验链路。
    test_feature_builder_does_not_use_future_available_returns = LegacyPipelineTest.test_feature_builder_does_not_use_future_available_returns
    test_feature_builder_computes_drawdown_recovery_features = LegacyPipelineTest.test_feature_builder_computes_drawdown_recovery_features
    test_feature_builder_computes_return_stability_features = LegacyPipelineTest.test_feature_builder_computes_return_stability_features
    test_feature_builder_computes_observation_layer_candidate_factors = LegacyPipelineTest.test_feature_builder_computes_observation_layer_candidate_factors
    test_feature_builder_computes_second_batch_observation_factors = LegacyPipelineTest.test_feature_builder_computes_second_batch_observation_factors
    test_feature_builder_computes_manager_post_change_excess_delta = LegacyPipelineTest.test_feature_builder_computes_manager_post_change_excess_delta
    test_feature_builder_does_not_use_future_available_benchmark = LegacyPipelineTest.test_feature_builder_does_not_use_future_available_benchmark
    # 评分与摘要规则：关注横截面打分、缺失值中性处理和回测摘要字段口径。
    test_backtest_summary_includes_missing_return_diagnostics = LegacyPipelineTest.test_backtest_summary_includes_missing_return_diagnostics
    test_score_funds_respects_configured_category_factors = LegacyPipelineTest.test_score_funds_respects_configured_category_factors
    test_score_funds_assigns_neutral_score_for_missing_event_factor = LegacyPipelineTest.test_score_funds_assigns_neutral_score_for_missing_event_factor
    test_score_funds_respects_direction_for_new_observation_fields = LegacyPipelineTest.test_score_funds_respects_direction_for_new_observation_fields
    # 经理、分类与单因子评价属于可局部推理的业务规则，适合放在 unit 组快速回归。
    test_manager_tenure_uses_real_manager_start_month = LegacyPipelineTest.test_manager_tenure_uses_real_manager_start_month
    test_manager_tenure_prefers_monthly_manager_assignment = LegacyPipelineTest.test_manager_tenure_prefers_monthly_manager_assignment
    test_manager_tenure_falls_back_or_clamps_on_bad_manager_start_month = LegacyPipelineTest.test_manager_tenure_falls_back_or_clamps_on_bad_manager_start_month
    test_fund_type_classifier_distinguishes_active_index_and_mixed_styles = LegacyPipelineTest.test_fund_type_classifier_distinguishes_active_index_and_mixed_styles
    test_fund_type_classifier_marks_unknown_case_as_low_confidence_other = LegacyPipelineTest.test_fund_type_classifier_marks_unknown_case_as_low_confidence_other
    test_factor_evaluation_respects_factor_direction = LegacyPipelineTest.test_factor_evaluation_respects_factor_direction
    test_factor_evaluation_skips_months_without_next_return = LegacyPipelineTest.test_factor_evaluation_skips_months_without_next_return
    test_factor_evaluation_distribution_and_correlation_handle_constant_and_missing_values = LegacyPipelineTest.test_factor_evaluation_distribution_and_correlation_handle_constant_and_missing_values
